services:
  web:
    build: .
    container_name: my-first-project-web-1
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: my-first-project-db-1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

